FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copier les fichiers de projet
COPY *.csproj ./
RUN dotnet restore

# Copier le reste des fichiers
COPY . ./
RUN dotnet publish -c Release -o out

# Image d'exécution
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app/out .

# Variables d'environnement
ENV TelegramBotToken=""
ENV DB_CONNECTION_STRING=""

CMD ["dotnet", "CisseSolutionBot.dll"]